// <auto-generated />
namespace IStudyKindergardens.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LiiitleChange5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LiiitleChange5));
        
        string IMigrationMetadata.Id
        {
            get { return "201803231707412_LiiitleChange5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
