// <auto-generated />
namespace IStudyKindergardens.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LittleChange5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LittleChange5));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121144277_LittleChange5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
